<wsdl:definitions
     name="SCM_MFG_WO_FETCH_BY_Query_DB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ModernManufacturing_v1_111171/Poll_SCM_Manufacturing_WorkOrders/SCM_MFG_WO_FETCH_BY_Query_DB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/ModernManufacturing_v1_111171/Poll_SCM_Manufacturing_WorkOrders/SCM_MFG_WO_FETCH_BY_Query_DB"
     xmlns:imp1="http://xmlns.oracle.com/pcbpel/adapter/db/top/POLL_SCM_WIE_WORK_ORDERS_V"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="Produce_Message_plt" >
    <plt:role name="Produce_Message_role" >
      <plt:portType name="tns:Produce_Message_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/POLL_SCM_WIE_WORK_ORDERS_V" schemaLocation="xsd/POLL_SCM_WIE_WORK_ORDERS_V_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Produce_Message_msg">
        <wsdl:part name="body" element="imp1:WieWorkOrdersVCollection"/>
    </wsdl:message>
    <wsdl:portType name="Produce_Message_ptt">
        <wsdl:operation name="Produce_Message">
            <wsdl:input message="tns:Produce_Message_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
