<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../SCM_MFG_WO_FETCH_BY_getWorkOrder_WS.wsdl"/>
      <rootElement name="WieWorkOrdersVCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/POLL_SCM_WIE_WORK_ORDERS_V"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../FETCH_WORK_ORDER_DETAILS.wsdl"/>
      <rootElement name="WieWorkOrdersVCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/POLL_SCM_WIE_WORK_ORDERS_V"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU AUG 11 12:03:00 IST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:imp1="http://xmlns.oracle.com/pcbpel/adapter/db/top/POLL_SCM_WIE_WORK_ORDERS_V"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/ModernManufacturing_v1_111171/Fetch_SCM_MFG_WO_By_getWorkOrder/SCM_MFG_WO_FETCH_BY_getWorkOrder_WS"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:client="http://xmlns.oracle.com/ModernManufacturing_v1_111171/Fetch_SCM_MFG_WO_By_getWorkOrder/FETCH_WORK_ORDER_DETAILS"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl imp1 pc plt wsdl tns jca xsd plnk client aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <imp1:WieWorkOrdersVCollection>
      <xsl:for-each select="/imp1:WieWorkOrdersVCollection/imp1:WieWorkOrdersV">
        <imp1:WieWorkOrdersV>
          <imp1:rowId>
            <xsl:if test="imp1:rowId/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="imp1:rowId/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="imp1:rowId"/>
          </imp1:rowId>
          <xsl:if test="imp1:objectVersionNumber">
            <imp1:objectVersionNumber>
              <xsl:value-of select="imp1:objectVersionNumber"/>
            </imp1:objectVersionNumber>
          </xsl:if>
          <xsl:if test="imp1:organizationId">
            <imp1:organizationId>
              <xsl:value-of select="imp1:organizationId"/>
            </imp1:organizationId>
          </xsl:if>
          <xsl:if test="imp1:workOrderId">
            <imp1:workOrderId>
              <xsl:value-of select="imp1:workOrderId"/>
            </imp1:workOrderId>
          </xsl:if>
          <xsl:if test="imp1:workOrderNumber">
            <imp1:workOrderNumber>
              <xsl:value-of select="imp1:workOrderNumber"/>
            </imp1:workOrderNumber>
          </xsl:if>
          <xsl:if test="imp1:workOrderDescription">
            <imp1:workOrderDescription>
              <xsl:if test="imp1:workOrderDescription/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:workOrderDescription/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:workOrderDescription"/>
            </imp1:workOrderDescription>
          </xsl:if>
          <xsl:if test="imp1:workMethodId">
            <imp1:workMethodId>
              <xsl:value-of select="imp1:workMethodId"/>
            </imp1:workMethodId>
          </xsl:if>
          <xsl:if test="imp1:workMethodCode">
            <imp1:workMethodCode>
              <xsl:value-of select="imp1:workMethodCode"/>
            </imp1:workMethodCode>
          </xsl:if>
          <xsl:if test="imp1:workOrderType">
            <imp1:workOrderType>
              <xsl:value-of select="imp1:workOrderType"/>
            </imp1:workOrderType>
          </xsl:if>
          <xsl:if test="imp1:workOrderSubType">
            <imp1:workOrderSubType>
              <xsl:if test="imp1:workOrderSubType/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:workOrderSubType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:workOrderSubType"/>
            </imp1:workOrderSubType>
          </xsl:if>
          <xsl:if test="imp1:inventoryItemId">
            <imp1:inventoryItemId>
              <xsl:value-of select="imp1:inventoryItemId"/>
            </imp1:inventoryItemId>
          </xsl:if>
          <xsl:if test="imp1:itemRevision">
            <imp1:itemRevision>
              <xsl:if test="imp1:itemRevision/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:itemRevision/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:itemRevision"/>
            </imp1:itemRevision>
          </xsl:if>
          <xsl:if test="imp1:workDefinitionAsOfDate">
            <imp1:workDefinitionAsOfDate>
              <xsl:if test="imp1:workDefinitionAsOfDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:workDefinitionAsOfDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:workDefinitionAsOfDate"/>
            </imp1:workDefinitionAsOfDate>
          </xsl:if>
          <xsl:if test="imp1:workDefinitionId">
            <imp1:workDefinitionId>
              <xsl:if test="imp1:workDefinitionId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:workDefinitionId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:workDefinitionId"/>
            </imp1:workDefinitionId>
          </xsl:if>
          <xsl:if test="imp1:workDefinitionVersionId">
            <imp1:workDefinitionVersionId>
              <xsl:if test="imp1:workDefinitionVersionId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:workDefinitionVersionId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:workDefinitionVersionId"/>
            </imp1:workDefinitionVersionId>
          </xsl:if>
          <xsl:if test="imp1:workOrderPriority">
            <imp1:workOrderPriority>
              <xsl:if test="imp1:workOrderPriority/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:workOrderPriority/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:workOrderPriority"/>
            </imp1:workOrderPriority>
          </xsl:if>
          <xsl:if test="imp1:workOrderStatusId">
            <imp1:workOrderStatusId>
              <xsl:value-of select="imp1:workOrderStatusId"/>
            </imp1:workOrderStatusId>
          </xsl:if>
          <xsl:if test="imp1:userStatusCode">
            <imp1:userStatusCode>
              <xsl:value-of select="imp1:userStatusCode"/>
            </imp1:userStatusCode>
          </xsl:if>
          <xsl:if test="imp1:systemStatusCode">
            <imp1:systemStatusCode>
              <xsl:value-of select="imp1:systemStatusCode"/>
            </imp1:systemStatusCode>
          </xsl:if>
          <xsl:if test="imp1:schedulingMethod">
            <imp1:schedulingMethod>
              <xsl:value-of select="imp1:schedulingMethod"/>
            </imp1:schedulingMethod>
          </xsl:if>
          <xsl:if test="imp1:plannedStartQuantity">
            <imp1:plannedStartQuantity>
              <xsl:value-of select="imp1:plannedStartQuantity"/>
            </imp1:plannedStartQuantity>
          </xsl:if>
          <xsl:if test="imp1:nettableSupplyQtyOverride">
            <imp1:nettableSupplyQtyOverride>
              <xsl:if test="imp1:nettableSupplyQtyOverride/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:nettableSupplyQtyOverride/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:nettableSupplyQtyOverride"/>
            </imp1:nettableSupplyQtyOverride>
          </xsl:if>
          <xsl:if test="imp1:uomCode">
            <imp1:uomCode>
              <xsl:value-of select="imp1:uomCode"/>
            </imp1:uomCode>
          </xsl:if>
          <xsl:if test="imp1:firmPlannedFlag">
            <imp1:firmPlannedFlag>
              <xsl:value-of select="imp1:firmPlannedFlag"/>
            </imp1:firmPlannedFlag>
          </xsl:if>
          <xsl:if test="imp1:plannedStartDate">
            <imp1:plannedStartDate>
              <xsl:if test="imp1:plannedStartDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:plannedStartDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:plannedStartDate"/>
            </imp1:plannedStartDate>
          </xsl:if>
          <xsl:if test="imp1:plannedCompletionDate">
            <imp1:plannedCompletionDate>
              <xsl:if test="imp1:plannedCompletionDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:plannedCompletionDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:plannedCompletionDate"/>
            </imp1:plannedCompletionDate>
          </xsl:if>
          <xsl:if test="imp1:actualStartDate">
            <imp1:actualStartDate>
              <xsl:if test="imp1:actualStartDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:actualStartDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:actualStartDate"/>
            </imp1:actualStartDate>
          </xsl:if>
          <xsl:if test="imp1:actualCompletionDate">
            <imp1:actualCompletionDate>
              <xsl:if test="imp1:actualCompletionDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:actualCompletionDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:actualCompletionDate"/>
            </imp1:actualCompletionDate>
          </xsl:if>
          <xsl:if test="imp1:releasedDate">
            <imp1:releasedDate>
              <xsl:if test="imp1:releasedDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:releasedDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:releasedDate"/>
            </imp1:releasedDate>
          </xsl:if>
          <xsl:if test="imp1:closedDate">
            <imp1:closedDate>
              <xsl:if test="imp1:closedDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:closedDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:closedDate"/>
            </imp1:closedDate>
          </xsl:if>
          <xsl:if test="imp1:canceledDate">
            <imp1:canceledDate>
              <xsl:if test="imp1:canceledDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:canceledDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:canceledDate"/>
            </imp1:canceledDate>
          </xsl:if>
          <xsl:if test="imp1:canceledReason">
            <imp1:canceledReason>
              <xsl:if test="imp1:canceledReason/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:canceledReason/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:canceledReason"/>
            </imp1:canceledReason>
          </xsl:if>
          <xsl:if test="imp1:statusChangeReason">
            <imp1:statusChangeReason>
              <xsl:if test="imp1:statusChangeReason/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:statusChangeReason/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:statusChangeReason"/>
            </imp1:statusChangeReason>
          </xsl:if>
          <xsl:if test="imp1:completedQuantity">
            <imp1:completedQuantity>
              <xsl:if test="imp1:completedQuantity/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:completedQuantity/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:completedQuantity"/>
            </imp1:completedQuantity>
          </xsl:if>
          <xsl:if test="imp1:scrappedQuantity">
            <imp1:scrappedQuantity>
              <xsl:if test="imp1:scrappedQuantity/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:scrappedQuantity/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:scrappedQuantity"/>
            </imp1:scrappedQuantity>
          </xsl:if>
          <xsl:if test="imp1:rejectedQuantity">
            <imp1:rejectedQuantity>
              <xsl:if test="imp1:rejectedQuantity/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:rejectedQuantity/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:rejectedQuantity"/>
            </imp1:rejectedQuantity>
          </xsl:if>
          <xsl:if test="imp1:overcomplToleranceType">
            <imp1:overcomplToleranceType>
              <xsl:if test="imp1:overcomplToleranceType/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:overcomplToleranceType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:overcomplToleranceType"/>
            </imp1:overcomplToleranceType>
          </xsl:if>
          <xsl:if test="imp1:overcomplToleranceValue">
            <imp1:overcomplToleranceValue>
              <xsl:if test="imp1:overcomplToleranceValue/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:overcomplToleranceValue/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:overcomplToleranceValue"/>
            </imp1:overcomplToleranceValue>
          </xsl:if>
          <xsl:if test="imp1:complSubinventoryCode">
            <imp1:complSubinventoryCode>
              <xsl:if test="imp1:complSubinventoryCode/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:complSubinventoryCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:complSubinventoryCode"/>
            </imp1:complSubinventoryCode>
          </xsl:if>
          <xsl:if test="imp1:complLocatorId">
            <imp1:complLocatorId>
              <xsl:if test="imp1:complLocatorId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:complLocatorId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:complLocatorId"/>
            </imp1:complLocatorId>
          </xsl:if>
          <xsl:if test="imp1:supplyType">
            <imp1:supplyType>
              <xsl:if test="imp1:supplyType/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:supplyType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:supplyType"/>
            </imp1:supplyType>
          </xsl:if>
          <xsl:if test="imp1:serialTrackingFlag">
            <imp1:serialTrackingFlag>
              <xsl:value-of select="imp1:serialTrackingFlag"/>
            </imp1:serialTrackingFlag>
          </xsl:if>
          <xsl:if test="imp1:backToBackFlag">
            <imp1:backToBackFlag>
              <xsl:value-of select="imp1:backToBackFlag"/>
            </imp1:backToBackFlag>
          </xsl:if>
          <xsl:if test="imp1:orchestrationCode">
            <imp1:orchestrationCode>
              <xsl:if test="imp1:orchestrationCode/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:orchestrationCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:orchestrationCode"/>
            </imp1:orchestrationCode>
          </xsl:if>
          <xsl:if test="imp1:interfaceSourceCode">
            <imp1:interfaceSourceCode>
              <xsl:if test="imp1:interfaceSourceCode/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:interfaceSourceCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:interfaceSourceCode"/>
            </imp1:interfaceSourceCode>
          </xsl:if>
          <xsl:if test="imp1:scoSupplyOrderId">
            <imp1:scoSupplyOrderId>
              <xsl:if test="imp1:scoSupplyOrderId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:scoSupplyOrderId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:scoSupplyOrderId"/>
            </imp1:scoSupplyOrderId>
          </xsl:if>
          <xsl:if test="imp1:contractMfgFlag">
            <imp1:contractMfgFlag>
              <xsl:value-of select="imp1:contractMfgFlag"/>
            </imp1:contractMfgFlag>
          </xsl:if>
          <xsl:if test="imp1:cmPoHeaderId">
            <imp1:cmPoHeaderId>
              <xsl:if test="imp1:cmPoHeaderId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:cmPoHeaderId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:cmPoHeaderId"/>
            </imp1:cmPoHeaderId>
          </xsl:if>
          <xsl:if test="imp1:cmPoLineId">
            <imp1:cmPoLineId>
              <xsl:if test="imp1:cmPoLineId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:cmPoLineId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:cmPoLineId"/>
            </imp1:cmPoLineId>
          </xsl:if>
          <xsl:if test="imp1:cmPoLineLocId">
            <imp1:cmPoLineLocId>
              <xsl:if test="imp1:cmPoLineLocId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:cmPoLineLocId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:cmPoLineLocId"/>
            </imp1:cmPoLineLocId>
          </xsl:if>
          <xsl:if test="imp1:sourceSystemType">
            <imp1:sourceSystemType>
              <xsl:if test="imp1:sourceSystemType/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:sourceSystemType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:sourceSystemType"/>
            </imp1:sourceSystemType>
          </xsl:if>
          <xsl:if test="imp1:sourceSystemId">
            <imp1:sourceSystemId>
              <xsl:if test="imp1:sourceSystemId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:sourceSystemId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:sourceSystemId"/>
            </imp1:sourceSystemId>
          </xsl:if>
          <xsl:if test="imp1:sourceHeaderRef">
            <imp1:sourceHeaderRef>
              <xsl:if test="imp1:sourceHeaderRef/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:sourceHeaderRef/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:sourceHeaderRef"/>
            </imp1:sourceHeaderRef>
          </xsl:if>
          <xsl:if test="imp1:sourceHeaderRefId">
            <imp1:sourceHeaderRefId>
              <xsl:if test="imp1:sourceHeaderRefId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:sourceHeaderRefId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:sourceHeaderRefId"/>
            </imp1:sourceHeaderRefId>
          </xsl:if>
          <xsl:if test="imp1:sourceLineRef">
            <imp1:sourceLineRef>
              <xsl:if test="imp1:sourceLineRef/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:sourceLineRef/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:sourceLineRef"/>
            </imp1:sourceLineRef>
          </xsl:if>
          <xsl:if test="imp1:sourceLineRefId">
            <imp1:sourceLineRefId>
              <xsl:if test="imp1:sourceLineRefId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:sourceLineRefId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:sourceLineRefId"/>
            </imp1:sourceLineRefId>
          </xsl:if>
          <xsl:if test="imp1:orderLessFlag">
            <imp1:orderLessFlag>
              <xsl:value-of select="imp1:orderLessFlag"/>
            </imp1:orderLessFlag>
          </xsl:if>
          <xsl:if test="imp1:createdBy">
            <imp1:createdBy>
              <xsl:value-of select="imp1:createdBy"/>
            </imp1:createdBy>
          </xsl:if>
          <xsl:if test="imp1:creationDate">
            <imp1:creationDate>
              <xsl:value-of select="imp1:creationDate"/>
            </imp1:creationDate>
          </xsl:if>
          <xsl:if test="imp1:lastUpdatedBy">
            <imp1:lastUpdatedBy>
              <xsl:value-of select="imp1:lastUpdatedBy"/>
            </imp1:lastUpdatedBy>
          </xsl:if>
          <xsl:if test="imp1:lastUpdateDate">
            <imp1:lastUpdateDate>
              <xsl:value-of select="imp1:lastUpdateDate"/>
            </imp1:lastUpdateDate>
          </xsl:if>
          <xsl:if test="imp1:lastUpdateLogin">
            <imp1:lastUpdateLogin>
              <xsl:if test="imp1:lastUpdateLogin/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:lastUpdateLogin/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:lastUpdateLogin"/>
            </imp1:lastUpdateLogin>
          </xsl:if>
          <xsl:if test="imp1:attributeCategory">
            <imp1:attributeCategory>
              <xsl:if test="imp1:attributeCategory/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeCategory/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeCategory"/>
            </imp1:attributeCategory>
          </xsl:if>
          <xsl:if test="imp1:attributeChar1">
            <imp1:attributeChar1>
              <xsl:if test="imp1:attributeChar1/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar1"/>
            </imp1:attributeChar1>
          </xsl:if>
          <xsl:if test="imp1:attributeChar2">
            <imp1:attributeChar2>
              <xsl:if test="imp1:attributeChar2/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar2"/>
            </imp1:attributeChar2>
          </xsl:if>
          <xsl:if test="imp1:attributeChar3">
            <imp1:attributeChar3>
              <xsl:if test="imp1:attributeChar3/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar3"/>
            </imp1:attributeChar3>
          </xsl:if>
          <xsl:if test="imp1:attributeChar4">
            <imp1:attributeChar4>
              <xsl:if test="imp1:attributeChar4/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar4/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar4"/>
            </imp1:attributeChar4>
          </xsl:if>
          <xsl:if test="imp1:attributeChar5">
            <imp1:attributeChar5>
              <xsl:if test="imp1:attributeChar5/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar5/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar5"/>
            </imp1:attributeChar5>
          </xsl:if>
          <xsl:if test="imp1:attributeChar6">
            <imp1:attributeChar6>
              <xsl:if test="imp1:attributeChar6/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar6/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar6"/>
            </imp1:attributeChar6>
          </xsl:if>
          <xsl:if test="imp1:attributeChar7">
            <imp1:attributeChar7>
              <xsl:if test="imp1:attributeChar7/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar7/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar7"/>
            </imp1:attributeChar7>
          </xsl:if>
          <xsl:if test="imp1:attributeChar8">
            <imp1:attributeChar8>
              <xsl:if test="imp1:attributeChar8/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar8/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar8"/>
            </imp1:attributeChar8>
          </xsl:if>
          <xsl:if test="imp1:attributeChar9">
            <imp1:attributeChar9>
              <xsl:if test="imp1:attributeChar9/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar9/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar9"/>
            </imp1:attributeChar9>
          </xsl:if>
          <xsl:if test="imp1:attributeChar10">
            <imp1:attributeChar10>
              <xsl:if test="imp1:attributeChar10/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar10/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar10"/>
            </imp1:attributeChar10>
          </xsl:if>
          <xsl:if test="imp1:attributeChar11">
            <imp1:attributeChar11>
              <xsl:if test="imp1:attributeChar11/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar11/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar11"/>
            </imp1:attributeChar11>
          </xsl:if>
          <xsl:if test="imp1:attributeChar12">
            <imp1:attributeChar12>
              <xsl:if test="imp1:attributeChar12/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar12/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar12"/>
            </imp1:attributeChar12>
          </xsl:if>
          <xsl:if test="imp1:attributeChar13">
            <imp1:attributeChar13>
              <xsl:if test="imp1:attributeChar13/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar13/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar13"/>
            </imp1:attributeChar13>
          </xsl:if>
          <xsl:if test="imp1:attributeChar14">
            <imp1:attributeChar14>
              <xsl:if test="imp1:attributeChar14/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar14/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar14"/>
            </imp1:attributeChar14>
          </xsl:if>
          <xsl:if test="imp1:attributeChar15">
            <imp1:attributeChar15>
              <xsl:if test="imp1:attributeChar15/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar15/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar15"/>
            </imp1:attributeChar15>
          </xsl:if>
          <xsl:if test="imp1:attributeChar16">
            <imp1:attributeChar16>
              <xsl:if test="imp1:attributeChar16/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar16/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar16"/>
            </imp1:attributeChar16>
          </xsl:if>
          <xsl:if test="imp1:attributeChar17">
            <imp1:attributeChar17>
              <xsl:if test="imp1:attributeChar17/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar17/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar17"/>
            </imp1:attributeChar17>
          </xsl:if>
          <xsl:if test="imp1:attributeChar18">
            <imp1:attributeChar18>
              <xsl:if test="imp1:attributeChar18/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar18/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar18"/>
            </imp1:attributeChar18>
          </xsl:if>
          <xsl:if test="imp1:attributeChar19">
            <imp1:attributeChar19>
              <xsl:if test="imp1:attributeChar19/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar19/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar19"/>
            </imp1:attributeChar19>
          </xsl:if>
          <xsl:if test="imp1:attributeChar20">
            <imp1:attributeChar20>
              <xsl:if test="imp1:attributeChar20/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeChar20/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeChar20"/>
            </imp1:attributeChar20>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber1">
            <imp1:attributeNumber1>
              <xsl:if test="imp1:attributeNumber1/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber1"/>
            </imp1:attributeNumber1>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber2">
            <imp1:attributeNumber2>
              <xsl:if test="imp1:attributeNumber2/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber2"/>
            </imp1:attributeNumber2>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber3">
            <imp1:attributeNumber3>
              <xsl:if test="imp1:attributeNumber3/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber3"/>
            </imp1:attributeNumber3>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber4">
            <imp1:attributeNumber4>
              <xsl:if test="imp1:attributeNumber4/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber4/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber4"/>
            </imp1:attributeNumber4>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber5">
            <imp1:attributeNumber5>
              <xsl:if test="imp1:attributeNumber5/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber5/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber5"/>
            </imp1:attributeNumber5>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber6">
            <imp1:attributeNumber6>
              <xsl:if test="imp1:attributeNumber6/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber6/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber6"/>
            </imp1:attributeNumber6>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber7">
            <imp1:attributeNumber7>
              <xsl:if test="imp1:attributeNumber7/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber7/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber7"/>
            </imp1:attributeNumber7>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber8">
            <imp1:attributeNumber8>
              <xsl:if test="imp1:attributeNumber8/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber8/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber8"/>
            </imp1:attributeNumber8>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber9">
            <imp1:attributeNumber9>
              <xsl:if test="imp1:attributeNumber9/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber9/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber9"/>
            </imp1:attributeNumber9>
          </xsl:if>
          <xsl:if test="imp1:attributeNumber10">
            <imp1:attributeNumber10>
              <xsl:if test="imp1:attributeNumber10/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeNumber10/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeNumber10"/>
            </imp1:attributeNumber10>
          </xsl:if>
          <xsl:if test="imp1:attributeDate1">
            <imp1:attributeDate1>
              <xsl:if test="imp1:attributeDate1/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeDate1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeDate1"/>
            </imp1:attributeDate1>
          </xsl:if>
          <xsl:if test="imp1:attributeDate2">
            <imp1:attributeDate2>
              <xsl:if test="imp1:attributeDate2/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeDate2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeDate2"/>
            </imp1:attributeDate2>
          </xsl:if>
          <xsl:if test="imp1:attributeDate3">
            <imp1:attributeDate3>
              <xsl:if test="imp1:attributeDate3/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeDate3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeDate3"/>
            </imp1:attributeDate3>
          </xsl:if>
          <xsl:if test="imp1:attributeDate4">
            <imp1:attributeDate4>
              <xsl:if test="imp1:attributeDate4/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeDate4/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeDate4"/>
            </imp1:attributeDate4>
          </xsl:if>
          <xsl:if test="imp1:attributeDate5">
            <imp1:attributeDate5>
              <xsl:if test="imp1:attributeDate5/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeDate5/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeDate5"/>
            </imp1:attributeDate5>
          </xsl:if>
          <xsl:if test="imp1:attributeTimestamp1">
            <imp1:attributeTimestamp1>
              <xsl:if test="imp1:attributeTimestamp1/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeTimestamp1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeTimestamp1"/>
            </imp1:attributeTimestamp1>
          </xsl:if>
          <xsl:if test="imp1:attributeTimestamp2">
            <imp1:attributeTimestamp2>
              <xsl:if test="imp1:attributeTimestamp2/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeTimestamp2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeTimestamp2"/>
            </imp1:attributeTimestamp2>
          </xsl:if>
          <xsl:if test="imp1:attributeTimestamp3">
            <imp1:attributeTimestamp3>
              <xsl:if test="imp1:attributeTimestamp3/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeTimestamp3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeTimestamp3"/>
            </imp1:attributeTimestamp3>
          </xsl:if>
          <xsl:if test="imp1:attributeTimestamp4">
            <imp1:attributeTimestamp4>
              <xsl:if test="imp1:attributeTimestamp4/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeTimestamp4/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeTimestamp4"/>
            </imp1:attributeTimestamp4>
          </xsl:if>
          <xsl:if test="imp1:attributeTimestamp5">
            <imp1:attributeTimestamp5>
              <xsl:if test="imp1:attributeTimestamp5/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:attributeTimestamp5/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:attributeTimestamp5"/>
            </imp1:attributeTimestamp5>
          </xsl:if>
          <xsl:if test="imp1:requestId">
            <imp1:requestId>
              <xsl:if test="imp1:requestId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:requestId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:requestId"/>
            </imp1:requestId>
          </xsl:if>
          <xsl:if test="imp1:jobDefinitionName">
            <imp1:jobDefinitionName>
              <xsl:if test="imp1:jobDefinitionName/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:jobDefinitionName/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:jobDefinitionName"/>
            </imp1:jobDefinitionName>
          </xsl:if>
          <xsl:if test="imp1:jobDefinitionPackage">
            <imp1:jobDefinitionPackage>
              <xsl:if test="imp1:jobDefinitionPackage/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="imp1:jobDefinitionPackage/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="imp1:jobDefinitionPackage"/>
            </imp1:jobDefinitionPackage>
          </xsl:if>
        </imp1:WieWorkOrdersV>
      </xsl:for-each>
    </imp1:WieWorkOrdersVCollection>
  </xsl:template>
</xsl:stylesheet>
