<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ShipmentRequestEBSV1" targetNamespace="http://xmlns.oracle.com/EnterpriseServices/Core/ShipmentRequest/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ebs="http://xmlns.oracle.com/EnterpriseServices/Core/ShipmentRequest/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <wsdl:documentation>
      <name>External Interface Virtual Partners Composite - Shipment EBO</name>
      <docCategories>
         <category>Other</category>
      </docCategories>
   </wsdl:documentation>
   <plnk:partnerLinkType name="ShipmentRequest">
      <plnk:role name="ShipmentRequestEBS">
         <plnk:portType name="ebs:ShipmentRequestEBS"/>
      </plnk:role>
      <plnk:role name="ShipmentRequestEBSResponse">
         <plnk:portType name="ebs:ShipmentRequestEBSResponse"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://xmlns.oracle.com/EnterpriseServices/Core/ShipmentRequest/V1" location="oramds:/apps/aia/EnterpriseBusinessServiceLibrary/Core/EBO/ShipmentRequest/V1/ShipmentRequestEBSV1.wsdl"/>
</wsdl:definitions>
