<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../POLL_SCM_WIE_WORK_ORDERS_V.wsdl"/>
      <rootElement name="WieWorkOrdersVCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/POLL_SCM_WIE_WORK_ORDERS_V"/>
    </source>
    <source type="XSD">
      <schema location="../xsd/temporaryVariables.xsd"/>
      <rootElement name="tempVariables" namespace="http://www.example.org"/>
      <param name="tempVars" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../POLL_SCM_WIE_WORK_ORDERS_V.wsdl"/>
      <rootElement name="WieWorkOrdersVCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/POLL_SCM_WIE_WORK_ORDERS_V"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU AUG 11 19:50:08 IST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ModernManufacturing_v1_111171/Poll_SCM_Manufacturing_WorkOrders/POLL_SCM_WIE_WORK_ORDERS_V"
                xmlns:ns0="http://www.example.org"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/POLL_SCM_WIE_WORK_ORDERS_V"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ns0 top plt xsd wsdl xp20 bpws aia bpel mhdr oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:param name="tempVars"/>
  <xsl:template match="/">
    <top:WieWorkOrdersVCollection>
      <top:WieWorkOrdersV>
          <top:rowId>
            <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number(number($tempVars/ns0:tempVariables/ns0:loopCounter))]/top:rowId/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number(number($tempVars/ns0:tempVariables/ns0:loopCounter))]/top:rowId/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number(number($tempVars/ns0:tempVariables/ns0:loopCounter))]/top:rowId"/>
          </top:rowId>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:objectVersionNumber">
            <top:objectVersionNumber>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:objectVersionNumber"/>
            </top:objectVersionNumber>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:organizationId">
            <top:organizationId>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:organizationId"/>
            </top:organizationId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderId">
            <top:workOrderId>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderId"/>
            </top:workOrderId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderNumber">
            <top:workOrderNumber>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderNumber"/>
            </top:workOrderNumber>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderDescription">
            <top:workOrderDescription>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderDescription/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderDescription/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderDescription"/>
            </top:workOrderDescription>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workMethodId">
            <top:workMethodId>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workMethodId"/>
            </top:workMethodId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workMethodCode">
            <top:workMethodCode>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workMethodCode"/>
            </top:workMethodCode>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderType">
            <top:workOrderType>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderType"/>
            </top:workOrderType>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderSubType">
            <top:workOrderSubType>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderSubType/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderSubType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderSubType"/>
            </top:workOrderSubType>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:inventoryItemId">
            <top:inventoryItemId>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:inventoryItemId"/>
            </top:inventoryItemId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:itemRevision">
            <top:itemRevision>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:itemRevision/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:itemRevision/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:itemRevision"/>
            </top:itemRevision>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionAsOfDate">
            <top:workDefinitionAsOfDate>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionAsOfDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionAsOfDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionAsOfDate"/>
            </top:workDefinitionAsOfDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionId">
            <top:workDefinitionId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionId"/>
            </top:workDefinitionId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionVersionId">
            <top:workDefinitionVersionId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionVersionId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionVersionId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workDefinitionVersionId"/>
            </top:workDefinitionVersionId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderPriority">
            <top:workOrderPriority>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderPriority/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderPriority/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderPriority"/>
            </top:workOrderPriority>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderStatusId">
            <top:workOrderStatusId>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:workOrderStatusId"/>
            </top:workOrderStatusId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:userStatusCode">
            <top:userStatusCode>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:userStatusCode"/>
            </top:userStatusCode>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:systemStatusCode">
            <top:systemStatusCode>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:systemStatusCode"/>
            </top:systemStatusCode>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:schedulingMethod">
            <top:schedulingMethod>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:schedulingMethod"/>
            </top:schedulingMethod>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedStartQuantity">
            <top:plannedStartQuantity>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedStartQuantity"/>
            </top:plannedStartQuantity>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:nettableSupplyQtyOverride">
            <top:nettableSupplyQtyOverride>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:nettableSupplyQtyOverride/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:nettableSupplyQtyOverride/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:nettableSupplyQtyOverride"/>
            </top:nettableSupplyQtyOverride>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:uomCode">
            <top:uomCode>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:uomCode"/>
            </top:uomCode>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:firmPlannedFlag">
            <top:firmPlannedFlag>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:firmPlannedFlag"/>
            </top:firmPlannedFlag>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedStartDate">
            <top:plannedStartDate>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedStartDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedStartDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedStartDate"/>
            </top:plannedStartDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedCompletionDate">
            <top:plannedCompletionDate>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedCompletionDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedCompletionDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:plannedCompletionDate"/>
            </top:plannedCompletionDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:actualStartDate">
            <top:actualStartDate>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:actualStartDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:actualStartDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:actualStartDate"/>
            </top:actualStartDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:actualCompletionDate">
            <top:actualCompletionDate>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:actualCompletionDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:actualCompletionDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:actualCompletionDate"/>
            </top:actualCompletionDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:releasedDate">
            <top:releasedDate>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:releasedDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:releasedDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:releasedDate"/>
            </top:releasedDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:closedDate">
            <top:closedDate>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:closedDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:closedDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:closedDate"/>
            </top:closedDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:canceledDate">
            <top:canceledDate>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:canceledDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:canceledDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:canceledDate"/>
            </top:canceledDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:canceledReason">
            <top:canceledReason>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:canceledReason/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:canceledReason/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:canceledReason"/>
            </top:canceledReason>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:statusChangeReason">
            <top:statusChangeReason>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:statusChangeReason/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:statusChangeReason/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:statusChangeReason"/>
            </top:statusChangeReason>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:completedQuantity">
            <top:completedQuantity>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:completedQuantity/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:completedQuantity/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:completedQuantity"/>
            </top:completedQuantity>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:scrappedQuantity">
            <top:scrappedQuantity>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:scrappedQuantity/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:scrappedQuantity/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:scrappedQuantity"/>
            </top:scrappedQuantity>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:rejectedQuantity">
            <top:rejectedQuantity>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:rejectedQuantity/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:rejectedQuantity/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:rejectedQuantity"/>
            </top:rejectedQuantity>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:overcomplToleranceType">
            <top:overcomplToleranceType>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:overcomplToleranceType/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:overcomplToleranceType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:overcomplToleranceType"/>
            </top:overcomplToleranceType>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:overcomplToleranceValue">
            <top:overcomplToleranceValue>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:overcomplToleranceValue/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:overcomplToleranceValue/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:overcomplToleranceValue"/>
            </top:overcomplToleranceValue>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:complSubinventoryCode">
            <top:complSubinventoryCode>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:complSubinventoryCode/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:complSubinventoryCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:complSubinventoryCode"/>
            </top:complSubinventoryCode>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:complLocatorId">
            <top:complLocatorId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:complLocatorId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:complLocatorId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:complLocatorId"/>
            </top:complLocatorId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:supplyType">
            <top:supplyType>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:supplyType/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:supplyType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:supplyType"/>
            </top:supplyType>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:serialTrackingFlag">
            <top:serialTrackingFlag>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:serialTrackingFlag"/>
            </top:serialTrackingFlag>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:backToBackFlag">
            <top:backToBackFlag>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:backToBackFlag"/>
            </top:backToBackFlag>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:orchestrationCode">
            <top:orchestrationCode>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:orchestrationCode/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:orchestrationCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:orchestrationCode"/>
            </top:orchestrationCode>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:interfaceSourceCode">
            <top:interfaceSourceCode>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:interfaceSourceCode/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:interfaceSourceCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:interfaceSourceCode"/>
            </top:interfaceSourceCode>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:scoSupplyOrderId">
            <top:scoSupplyOrderId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:scoSupplyOrderId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:scoSupplyOrderId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:scoSupplyOrderId"/>
            </top:scoSupplyOrderId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:contractMfgFlag">
            <top:contractMfgFlag>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:contractMfgFlag"/>
            </top:contractMfgFlag>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoHeaderId">
            <top:cmPoHeaderId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoHeaderId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoHeaderId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoHeaderId"/>
            </top:cmPoHeaderId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoLineId">
            <top:cmPoLineId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoLineId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoLineId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoLineId"/>
            </top:cmPoLineId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoLineLocId">
            <top:cmPoLineLocId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoLineLocId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoLineLocId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:cmPoLineLocId"/>
            </top:cmPoLineLocId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceSystemType">
            <top:sourceSystemType>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceSystemType/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceSystemType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceSystemType"/>
            </top:sourceSystemType>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceSystemId">
            <top:sourceSystemId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceSystemId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceSystemId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceSystemId"/>
            </top:sourceSystemId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceHeaderRef">
            <top:sourceHeaderRef>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceHeaderRef/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceHeaderRef/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceHeaderRef"/>
            </top:sourceHeaderRef>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceHeaderRefId">
            <top:sourceHeaderRefId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceHeaderRefId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceHeaderRefId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceHeaderRefId"/>
            </top:sourceHeaderRefId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceLineRef">
            <top:sourceLineRef>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceLineRef/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceLineRef/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceLineRef"/>
            </top:sourceLineRef>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceLineRefId">
            <top:sourceLineRefId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceLineRefId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceLineRefId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:sourceLineRefId"/>
            </top:sourceLineRefId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:orderLessFlag">
            <top:orderLessFlag>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:orderLessFlag"/>
            </top:orderLessFlag>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:createdBy">
            <top:createdBy>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:createdBy"/>
            </top:createdBy>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:creationDate">
            <top:creationDate>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:creationDate"/>
            </top:creationDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:lastUpdatedBy">
            <top:lastUpdatedBy>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:lastUpdatedBy"/>
            </top:lastUpdatedBy>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:lastUpdateDate">
            <top:lastUpdateDate>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:lastUpdateDate"/>
            </top:lastUpdateDate>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:lastUpdateLogin">
            <top:lastUpdateLogin>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:lastUpdateLogin/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:lastUpdateLogin/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:lastUpdateLogin"/>
            </top:lastUpdateLogin>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeCategory">
            <top:attributeCategory>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeCategory/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeCategory/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeCategory"/>
            </top:attributeCategory>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar1">
            <top:attributeChar1>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar1/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar1"/>
            </top:attributeChar1>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar2">
            <top:attributeChar2>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar2/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar2"/>
            </top:attributeChar2>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar3">
            <top:attributeChar3>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar3/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar3"/>
            </top:attributeChar3>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar4">
            <top:attributeChar4>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar4/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar4/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar4"/>
            </top:attributeChar4>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar5">
            <top:attributeChar5>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar5/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar5/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar5"/>
            </top:attributeChar5>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar6">
            <top:attributeChar6>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar6/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar6/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar6"/>
            </top:attributeChar6>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar7">
            <top:attributeChar7>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar7/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar7/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar7"/>
            </top:attributeChar7>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar8">
            <top:attributeChar8>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar8/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar8/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar8"/>
            </top:attributeChar8>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar9">
            <top:attributeChar9>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar9/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar9/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar9"/>
            </top:attributeChar9>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar10">
            <top:attributeChar10>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar10/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar10/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar10"/>
            </top:attributeChar10>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar11">
            <top:attributeChar11>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar11/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar11/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar11"/>
            </top:attributeChar11>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar12">
            <top:attributeChar12>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar12/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar12/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar12"/>
            </top:attributeChar12>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar13">
            <top:attributeChar13>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar13/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar13/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar13"/>
            </top:attributeChar13>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar14">
            <top:attributeChar14>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar14/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar14/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar14"/>
            </top:attributeChar14>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar15">
            <top:attributeChar15>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar15/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar15/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar15"/>
            </top:attributeChar15>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar16">
            <top:attributeChar16>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar16/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar16/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar16"/>
            </top:attributeChar16>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar17">
            <top:attributeChar17>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar17/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar17/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar17"/>
            </top:attributeChar17>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar18">
            <top:attributeChar18>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar18/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar18/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar18"/>
            </top:attributeChar18>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar19">
            <top:attributeChar19>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar19/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar19/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar19"/>
            </top:attributeChar19>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar20">
            <top:attributeChar20>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar20/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar20/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeChar20"/>
            </top:attributeChar20>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber1">
            <top:attributeNumber1>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber1/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber1"/>
            </top:attributeNumber1>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber2">
            <top:attributeNumber2>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber2/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber2"/>
            </top:attributeNumber2>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber3">
            <top:attributeNumber3>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber3/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber3"/>
            </top:attributeNumber3>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber4">
            <top:attributeNumber4>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber4/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber4/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber4"/>
            </top:attributeNumber4>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber5">
            <top:attributeNumber5>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber5/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber5/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber5"/>
            </top:attributeNumber5>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber6">
            <top:attributeNumber6>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber6/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber6/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber6"/>
            </top:attributeNumber6>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber7">
            <top:attributeNumber7>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber7/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber7/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber7"/>
            </top:attributeNumber7>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber8">
            <top:attributeNumber8>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber8/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber8/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber8"/>
            </top:attributeNumber8>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber9">
            <top:attributeNumber9>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber9/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber9/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber9"/>
            </top:attributeNumber9>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber10">
            <top:attributeNumber10>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber10/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber10/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeNumber10"/>
            </top:attributeNumber10>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate1">
            <top:attributeDate1>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate1/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate1"/>
            </top:attributeDate1>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate2">
            <top:attributeDate2>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate2/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate2"/>
            </top:attributeDate2>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate3">
            <top:attributeDate3>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate3/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate3"/>
            </top:attributeDate3>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate4">
            <top:attributeDate4>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate4/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate4/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate4"/>
            </top:attributeDate4>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate5">
            <top:attributeDate5>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate5/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate5/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeDate5"/>
            </top:attributeDate5>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp1">
            <top:attributeTimestamp1>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp1/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp1"/>
            </top:attributeTimestamp1>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp2">
            <top:attributeTimestamp2>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp2/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp2"/>
            </top:attributeTimestamp2>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp3">
            <top:attributeTimestamp3>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp3/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp3"/>
            </top:attributeTimestamp3>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp4">
            <top:attributeTimestamp4>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp4/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp4/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp4"/>
            </top:attributeTimestamp4>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp5">
            <top:attributeTimestamp5>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp5/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp5/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:attributeTimestamp5"/>
            </top:attributeTimestamp5>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:requestId">
            <top:requestId>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:requestId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:requestId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:requestId"/>
            </top:requestId>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:jobDefinitionName">
            <top:jobDefinitionName>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:jobDefinitionName/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:jobDefinitionName/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:jobDefinitionName"/>
            </top:jobDefinitionName>
          </xsl:if>
          <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:jobDefinitionPackage">
            <top:jobDefinitionPackage>
              <xsl:if test="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:jobDefinitionPackage/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:jobDefinitionPackage/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/top:WieWorkOrdersVCollection/top:WieWorkOrdersV[number($tempVars/ns0:tempVariables/ns0:loopCounter)]/top:jobDefinitionPackage"/>
            </top:jobDefinitionPackage>
          </xsl:if>
        </top:WieWorkOrdersV>
    </top:WieWorkOrdersVCollection>
  </xsl:template>
</xsl:stylesheet>
